// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CC.Data;

public partial class DataContext : DbContext
{
    public DataContext(DbContextOptions<DataContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Group> Groups { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserAlbum> UserAlbums { get; set; }

    public virtual DbSet<UserGroup> UserGroups { get; set; }

    public virtual DbSet<UserGroupMessage> UserGroupMessages { get; set; }

    public virtual DbSet<UserMedium> UserMedia { get; set; }

    public virtual DbSet<UserMediumProfile> UserMediumProfiles { get; set; }

    public virtual DbSet<UserProfile> UserProfiles { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<User>(entity =>
        {
            entity.HasIndex(e => e.NormalizedUserName, "UserNameIndex")
                .IsUnique()
                .HasFilter("([NormalizedUserName] IS NOT NULL)");
        });

        modelBuilder.Entity<UserAlbum>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_Album");

            entity.Property(e => e.Id).ValueGeneratedOnAdd();

            entity.HasOne(d => d.IdNavigation).WithOne(p => p.UserAlbum)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserAlbum_UserMedium");

            entity.HasOne(d => d.User).WithMany(p => p.UserAlbums)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserAlbum_User");
        });

        modelBuilder.Entity<UserGroup>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_GroupUser");

            entity.HasOne(d => d.Group).WithMany(p => p.UserGroups)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Group_User");

            entity.HasOne(d => d.User).WithMany(p => p.UserGroups)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserGroup_User");
        });

        modelBuilder.Entity<UserGroupMessage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_GroupMessage");

            entity.HasOne(d => d.Group).WithMany(p => p.UserGroupMessages)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserGroupMessage_UserGroup");

            entity.HasOne(d => d.UserGroup).WithMany(p => p.UserGroupMessages)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserGroupMessage_UserGroupProfile");

            entity.HasOne(d => d.UserProfile).WithMany(p => p.UserGroupMessages)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserGroupMessage_UserProfile");
        });

        modelBuilder.Entity<UserMedium>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_Media");
        });

        modelBuilder.Entity<UserMediumProfile>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_UserMediumUserProfile");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.UserMedium).WithMany(p => p.UserMediumProfiles)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserMediumProfile_UserMedium");

            entity.HasOne(d => d.UserProfile).WithMany(p => p.UserMediumProfiles)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserMediumProfile_UserProfile");
        });

        modelBuilder.Entity<UserProfile>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_Member");

            entity.HasOne(d => d.User).WithMany(p => p.UserProfiles)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserProfile_User");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}