// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CC.Data;

public partial class Medium
{
    [Key]
    public int Id { get; set; }

    public int AlbumId { get; set; }

    [Required]
    [StringLength(450)]
    public string UserId { get; set; }

    [StringLength(50)]
    public string Name { get; set; }

    public string Text { get; set; }

    [ForeignKey("AlbumId")]
    [InverseProperty("Media")]
    public virtual Album Album { get; set; }

    [InverseProperty("Media")]
    public virtual ICollection<MediaTag> MediaTags { get; } = new List<MediaTag>();

    [ForeignKey("UserId")]
    [InverseProperty("Media")]
    public virtual User User { get; set; }
}