// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CC.Data;

[Table("MediaTag")]
public partial class MediaTag
{
    [Key]
    public int Id { get; set; }

    public int MediaId { get; set; }

    public int MemberId { get; set; }

    public bool HasAuthorized { get; set; }

    [ForeignKey("MediaId")]
    [InverseProperty("MediaTags")]
    public virtual Medium Media { get; set; }
}