// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CC.Data;

[Table("Member")]
public partial class Member
{
    [Key]
    [Column("Member")]
    public int Member1 { get; set; }

    [Required]
    [StringLength(450)]
    public string UserId { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    public DateTime Birthdate { get; set; }

    public int? Weight { get; set; }

    public int? EyesColor { get; set; }

    public int? HairsColor { get; set; }

    public int? Job { get; set; }

    public int? Smoker { get; set; }

    public int? Trend { get; set; }

    public int? Ethnicity { get; set; }

    public bool? IsActive { get; set; }

    public int? Body { get; set; }
}