// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CC.Data;

[Table("UserMedium")]
public partial class UserMedium
{
    [Key]
    public int Id { get; set; }

    public int AlbumId { get; set; }

    [StringLength(50)]
    public string Name { get; set; }

    public string Text { get; set; }

    [InverseProperty("IdNavigation")]
    public virtual UserAlbum UserAlbum { get; set; }

    [InverseProperty("UserMedium")]
    public virtual ICollection<UserMediumProfile> UserMediumProfiles { get; set; } = new List<UserMediumProfile>();
}