// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CC.Data;

[Table("UserProfile")]
public partial class UserProfile
{
    [Key]
    public string Id { get; set; }

    [Required]
    [StringLength(450)]
    public string UserId { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    public DateTime? Birthdate { get; set; }

    public int? Weight { get; set; }

    public int? EyesColor { get; set; }

    public int? HairsColor { get; set; }

    public int? Job { get; set; }

    public int? Smoker { get; set; }

    public int? Trend { get; set; }

    public int? Ethnicity { get; set; }

    public bool? IsActive { get; set; }

    public int? Body { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("UserProfiles")]
    public virtual User User { get; set; }

    [InverseProperty("UserProfile")]
    public virtual ICollection<UserGroupMessage> UserGroupMessages { get; set; } = new List<UserGroupMessage>();

    [InverseProperty("UserProfile")]
    public virtual ICollection<UserMediumProfile> UserMediumProfiles { get; set; } = new List<UserMediumProfile>();
}