// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CC.Data;

[Table("UserGroup")]
public partial class UserGroup
{
    [Key]
    public int Id { get; set; }

    public int GroupId { get; set; }

    [Required]
    [StringLength(450)]
    public string UserId { get; set; }

    [ForeignKey("GroupId")]
    [InverseProperty("UserGroups")]
    public virtual Group Group { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("UserGroups")]
    public virtual User User { get; set; }

    [InverseProperty("UserGroup")]
    public virtual ICollection<UserGroupMessage> UserGroupMessages { get; set; } = new List<UserGroupMessage>();
}