// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CC.Data;

[Table("UserGroupProfile")]
public partial class UserGroupProfile
{
    [Key]
    public int Id { get; set; }

    public int UserGroupId { get; set; }

    public int UserProfileId { get; set; }

    [ForeignKey("UserGroupId")]
    [InverseProperty("UserGroupProfiles")]
    public virtual UserGroup UserGroup { get; set; }

    [InverseProperty("UserGroupProfile")]
    public virtual ICollection<UserGroupMessage> UserGroupMessages { get; set; } = new List<UserGroupMessage>();

    [ForeignKey("UserProfileId")]
    [InverseProperty("UserGroupProfiles")]
    public virtual UserProfile UserProfile { get; set; }
}