// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CC.Data;

[Table("UserGroup")]
public partial class UserGroup
{
    [Key]
    public int Id { get; set; }

    public int UserGroupId { get; set; }

    [Required]
    [StringLength(450)]
    public string UserId { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("UserGroups")]
    public virtual User User { get; set; }

    [InverseProperty("UserGroupProfile")]
    public virtual ICollection<UserGroupMessage> UserGroupMessages { get; set; } = new List<UserGroupMessage>();

    [ForeignKey("UserGroupId")]
    [InverseProperty("UserGroups")]
    public virtual Group UserGroupNavigation { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("UserGroups")]
    public virtual UserProfile UserNavigation { get; set; }
}