// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CC.Data;

[Table("UserGroupMessage")]
public partial class UserGroupMessage
{
    [Key]
    public int Id { get; set; }

    public int UserGroupId { get; set; }

    public int UserGroupProfileId { get; set; }

    [Required]
    public string Message { get; set; }

    [ForeignKey("UserGroupId")]
    [InverseProperty("UserGroupMessages")]
    public virtual UserGroup UserGroup { get; set; }

    [ForeignKey("UserGroupProfileId")]
    [InverseProperty("UserGroupMessages")]
    public virtual UserGroupProfile UserGroupProfile { get; set; }
}