// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CC.Data;

[Table("UserMediumProfile")]
public partial class UserMediumProfile
{
    [Key]
    public int Id { get; set; }

    public int UserMediumId { get; set; }

    public int UserProfileId { get; set; }

    [ForeignKey("UserMediumId")]
    [InverseProperty("UserMediumProfiles")]
    public virtual UserMedium UserMedium { get; set; }

    [ForeignKey("UserProfileId")]
    [InverseProperty("UserMediumProfiles")]
    public virtual UserProfile UserProfile { get; set; }
}